server:
  port: 8281

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/auth/**
            - id: user-service
              uri: lb://user-service
              predicates:
                  - Path=/api/v1/user/**
