server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:3678/auth_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-Auto: update
    defer-datasource-initialization: true
    showSql: true
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true

logging:
  level:
    com.auth: DEBUG
    org.springframework.kafka: INFO